name: Production CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  prod-deploy:
    uses: ./.github/workflows/ci_cd_base.yml
    with:
      environment: prod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
